In [1]:
import os
import pandas as pd
import glob
import matplotlib.pyplot as plt

In [2]:
# 데이터 읽기 및 NaN 값 처리
val = pd.read_csv('val_24hr_median_0628.csv', low_memory=False)
val_label = pd.read_csv('val_label.csv', low_memory=False)

# 데이터 읽기 및 NaN 값 처리
test = pd.read_csv('test_24hr_median_0628.csv', low_memory=False)

test

,subject_id,datetime,level_2,x_last,x_mean,x_max,x_min,x_median,y_last,y_mean,...,HRV_IQRNN,HRV_SDRMSSD,HRV_Prc20NN,HRV_Prc80NN,HRV_pNN50,HRV_pNN20,HRV_MinNN,HRV_MaxNN,HRV_HTI,HRV_TINN
0,5.0,2023-11-05,0,-0.040701,-0.065710,1.574188,-1.702277,-0.064643,0.175974,0.184720,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1,5.0,2023-11-06,0,0.028730,0.003530,1.690306,-0.938527,0.019752,0.414197,0.440236,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
2,5.0,2023-11-07,0,0.052672,0.038821,0.417788,-0.201113,0.041899,0.156820,0.168071,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
3,5.0,2023-11-08,0,-0.059855,-0.066900,0.238223,-0.715866,-0.069432,0.210690,0.217838,...,0.000000,0.000000,10000.000000,10000.000000,0.000000,0.000000,10000.000000,10000.000000,1.000000,0.0
4,5.0,2023-11-09,0,-0.390255,-0.376375,0.055067,-1.380257,-0.375890,0.294487,0.300855,...,16.666667,9.708690,12333.333333,12350.000000,0.208333,0.208333,10000.000000,12666.666667,1.716329,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,8.0,2023-11-05,0,0.126897,0.118722,0.265765,0.011971,0.119714,0.186753,0.185070,...,13358.333333,3.138471,11100.000000,25966.666667,93.667158,94.256259,8850.000000,31733.333333,42.437500,0.0
117,8.0,2023-11-06,0,-1.893871,-1.592407,0.011971,-8.382356,-1.468888,4.680807,4.672112,...,1600.000000,0.877626,10150.000000,12200.000000,91.330891,93.162393,8266.666667,28166.666667,35.608696,0.0
118,8.0,2023-11-07,0,0.189148,0.188317,0.284919,0.099362,0.189148,0.095771,0.101851,...,3241.666667,1.940019,10983.333333,19526.666667,82.622601,83.475480,5516.666667,30316.666667,39.083333,0.0
119,8.0,2023-11-08,0,0.385478,0.383590,0.823631,0.325621,0.385478,0.349564,0.350324,...,12400.000000,3.789745,10050.000000,24100.000000,83.501006,84.708249,7066.666667,30316.666667,45.181818,0.0
120,8.0,2023-11-09,0,0.395055,0.397442,0.438152,0.361536,0.397450,0.318439,0.317787,...,11116.666667,1.562951,11100.000000,23000.000000,94.928230,95.023923,8066.666667,32250.000000,27.500000,0.0

In [3]:
val

,subject_id,datetime,level_2,x_last,x_mean,x_max,x_min,x_median,y_last,y_mean,...,HRV_IQRNN,HRV_SDRMSSD,HRV_Prc20NN,HRV_Prc80NN,HRV_pNN50,HRV_pNN20,HRV_MinNN,HRV_MaxNN,HRV_HTI,HRV_TINN
0,1.0,2023-08-20,0,0.133998,0.219183,0.981057,-0.765703,0.150748,0.413958,0.428777,...,3033.333333,1.407370,11500.000000,15296.666667,92.416452,92.416452,7933.333333,21283.333333,29.923077,0.0
1,1.0,2023-08-21,0,0.129212,0.169542,1.319642,-1.676172,0.140578,-0.009571,-0.013229,...,2233.333333,1.326863,10533.333333,13333.333333,94.146341,94.146341,6800.000000,20833.333333,24.848485,0.0
2,1.0,2023-08-22,0,1.045664,1.056068,1.262214,-0.154337,1.050449,-1.746760,-1.750896,...,2333.333333,1.268400,11116.666667,14083.333333,88.986233,88.986233,8333.333333,27033.333333,24.212121,0.0
3,1.0,2023-08-23,0,0.795614,0.882982,6.075376,-0.905683,0.757328,0.032901,0.044782,...,3033.333333,1.188516,10983.333333,14700.000000,95.137976,95.137976,8850.000000,31250.000000,34.590909,0.0
4,1.0,2023-08-24,0,-0.062213,-0.032638,1.344766,-1.586441,-0.033500,-0.111266,-0.112217,...,2783.333333,1.273447,11350.000000,14700.000000,93.597951,93.597951,9166.666667,20000.000000,30.038462,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,4.0,2023-10-28,0,-0.112463,-0.107684,0.055035,-0.370588,-0.106481,0.153141,0.147873,...,2354.166667,1.395229,11100.000000,13900.000000,87.837838,87.837838,7400.000000,16666.666667,19.028571,0.0
115,4.0,2023-10-29,0,-0.155533,-0.153937,0.101695,-0.295813,-0.153141,0.215952,0.228002,...,2433.333333,1.410029,11766.666667,14700.000000,91.545575,91.545575,6900.000000,17850.000000,18.925000,0.0
116,4.0,2023-10-30,0,-0.070588,-0.072888,0.120239,-0.108873,-0.072981,-0.499203,-0.502537,...,2116.666667,1.314941,11366.666667,14083.333333,90.243902,90.243902,6750.000000,16950.000000,20.500000,0.0
117,4.0,2023-10-31,0,3.393621,3.399032,3.449852,3.357728,3.399603,-1.036690,-1.047051,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
118,4.0,2023-11-01,0,0.050847,0.054336,0.226122,-0.210568,0.047258,-0.457328,-0.438325,...,4133.333333,3.044311,6383.333333,13166.666667,66.847237,67.605634,5350.000000,15383.333333,16.192982,0.0

In [4]:
val.drop(columns=['level_2'],inplace=True)
test.drop(columns=['level_2'],inplace=True)

In [5]:
val.keys()

Index(['subject_id', 'datetime', 'x_last', 'x_mean', 'x_max', 'x_min',
       'x_median', 'y_last', 'y_mean', 'y_max', 'y_min', 'y_median', 'z_last',
       'z_mean', 'z_max', 'z_min', 'z_median', 'speed_last', 'speed_mean',
       'speed_max', 'speed_min', 'speed_median', 'm_light', 'heart_rate_last',
       'heart_rate_mean', 'heart_rate_max', 'heart_rate_min',
       'heart_rate_median', 'w_light', 'burned_calories', 'distance',
       'running_steps', 'speed', 'steps', 'step_frequency', 'walking_steps',
       'm_activity', 'altitude_last', 'altitude_mean', 'altitude_max',
       'altitude_min', 'altitude_median', 'latitude_last', 'latitude_mean',
       'latitude_max', 'latitude_min', 'latitude_median', 'longitude_last',
       'longitude_mean', 'longitude_max', 'longitude_min', 'longitude_median',
       'day_location_entropy', 'day_Movement_radius', 'HRV_MeanNN', 'HRV_SDNN',
       'HRV_SDANN1', 'HRV_SDNNI1', 'HRV_SDANN2', 'HRV_SDNNI2', 'HRV_SDANN5',
       'HRV_SDNNI5', 'HRV_RMSSD', 'HRV_SDSD', 'HRV_CVNN', 'HRV_CVSD',
       'HRV_MedianNN', 'HRV_MadNN', 'HRV_MCVNN', 'HRV_IQRNN', 'HRV_SDRMSSD',
       'HRV_Prc20NN', 'HRV_Prc80NN', 'HRV_pNN50', 'HRV_pNN20', 'HRV_MinNN',
       'HRV_MaxNN', 'HRV_HTI', 'HRV_TINN'],
      dtype='object')

In [6]:
val_label_copy = val_label.copy()

val_label_copy

     subject_id        date  Q1  Q2  Q3  S1  S2  S3  S4
0             1  2023-08-20   1   1   1   0   0   0   0
1             1  2023-08-21   1   1   1   0   0   1   0
2             1  2023-08-22   0   1   1   0   1   1   0
3             1  2023-08-23   0   1   1   0   0   1   0
4             1  2023-08-24   1   1   1   0   0   1   0
..          ...         ...  ..  ..  ..  ..  ..  ..  ..
100           4  2023-10-27   0   1   0   0   1   1   1
101           4  2023-10-28   1   1   0   1   1   1   1
102           4  2023-10-29   1   1   0   0   1   1   1
103           4  2023-10-30   0   1   0   0   0   1   1
104           4  2023-11-01   1   1   0   0   1   1   1

[105 rows x 9 columns]

In [7]:
# 열 이름 변경
val_label_copy.rename(columns={'subject_id': 'user'}, inplace=True)
val.rename(columns={'subject_id': 'user'}, inplace=True)

# label 데이터의 user 형식을 숫자로 변환하는 함수
def convert_user_to_number(user_str):
    if isinstance(user_str, str):
        return int(user_str.replace('user', ''))
    elif isinstance(user_str, float):
        return int(user_str)
    return user_str

val_label_copy['user'] = val_label_copy['user'].apply(convert_user_to_number)

val_label_copy['user']

0      1
1      1
2      1
3      1
4      1
      ..
100    4
101    4
102    4
103    4
104    4
Name: user, Length: 105, dtype: int64

In [8]:
# 'datetime' 열을 datetime 타입으로 변환
val_label_copy['datetime'] = pd.to_datetime(val_label_copy['date'])
val['datetime'] = pd.to_datetime(val['datetime'])

# 인덱스 설정
val.set_index(['datetime', 'user'], inplace=True)
val_label_copy.set_index('datetime', inplace=True)

# 사용자별 최소 및 최대 시간 추출
user_times = val_label_copy.groupby('user').apply(lambda x: (x.index.min(), x.index.max()))

# 전체 시간대 인덱스 생성 및 데이터프레임 생성
all_dfs = []
for user, (start, end) in user_times.items():
    all_times = pd.date_range(start=start, end=end, freq='24H')
    user_df = pd.DataFrame(index=all_times, columns=['value'])
    user_df.index.name = 'datetime'
    user_df['user'] = user
    user_df.set_index('user', append=True, inplace=True)
    all_dfs.append(user_df)

all_df = pd.concat(all_dfs)

# 데이터프레임 병합
# 정렬을 확인합니다.
all_df = all_df.sort_index()
val = val.sort_index()

# 데이터프레임을 병합합니다.
full_df = all_df.combine_first(val)
full_df = full_df.reset_index()

# 필요한 칼럼에 따라 정렬

# 사용자별 그룹화 후 datetime 기준으로 정렬
full_df = full_df.sort_values(by=['user', 'datetime'])
full_df

C:\Users\lty\AppData\Local\Temp\ipykernel_18356\11214188.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  user_times = val_label_copy.groupby('user').apply(lambda x: (x.index.min(), x.index.max()))
C:\Users\lty\AppData\Local\Temp\ipykernel_18356\11214188.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  all_times = pd.date_range(start=start, end=end, freq='24H')
C:\Users\lty\AppData\Local\Temp\ipykernel_18356\11214188.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  all_times = pd.date_range(start=start, end=end, freq='24H')
C:\Users\lty\AppData\Local\Temp\ipykernel_18356\11214188.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  all_times = pd.date_range(start=start, end=end, freq='24H')
C:\Users\lty\AppData\Local\Temp\ipykernel_18356\11214188.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  all_times = pd.date_range(start=start, end=end, freq='24H')

,datetime,user,HRV_CVNN,HRV_CVSD,HRV_HTI,HRV_IQRNN,HRV_MCVNN,HRV_MadNN,HRV_MaxNN,HRV_MeanNN,...,y_last,y_max,y_mean,y_median,y_min,z_last,z_max,z_mean,z_median,z_min
0,2023-08-20,1,0.153625,0.109158,29.923077,3033.333333,0.176059,2347.45,21283.333333,13417.266495,...,0.413958,1.036092,0.428777,0.378066,-0.038285,9.165707,9.863214,8.861109,9.157333,5.048856
1,2023-08-21,1,0.144754,0.109095,24.848485,2233.333333,0.134971,1606.15,20833.333333,11963.211382,...,-0.009571,0.181855,-0.013229,-0.014357,-0.339781,9.427721,9.872787,9.377162,9.422935,5.424529
2,2023-08-22,1,0.159191,0.125505,24.212121,2333.333333,0.140057,1729.70,27033.333333,12754.359616,...,-1.746760,-0.062213,-1.750896,-1.751546,-2.050649,8.276774,9.643075,7.798959,8.160721,5.877969
3,2023-08-23,1,0.202594,0.170459,34.590909,3033.333333,0.164074,2050.93,31250.000000,13062.658782,...,0.032901,0.537189,0.044782,0.043071,-1.094716,3.798606,9.402596,3.411778,3.293720,-1.805385
4,2023-08-24,1,0.141836,0.111380,30.038462,2783.333333,0.154237,1976.80,20000.000000,12995.646607,...,-0.111266,0.105284,-0.112217,-0.110070,-0.356531,9.543774,9.872787,8.913097,9.510274,6.374479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,2023-10-28,4,0.130010,0.093182,19.028571,2354.166667,0.123229,1581.44,16666.666667,12598.848849,...,0.153141,0.295813,0.147873,0.148355,-0.111864,-4.267001,-4.227519,-4.263600,-4.264010,-4.357330
115,2023-10-29,4,0.136587,0.096868,18.925000,2433.333333,0.127874,1704.99,17850.000000,13126.662263,...,0.215952,0.338884,0.228002,0.197408,0.129212,0.581755,5.991777,0.579075,0.579362,-4.528417
116,2023-10-30,4,0.129085,0.098168,20.500000,2116.666667,0.123709,1606.15,16950.000000,12684.603659,...,-0.499203,-0.364008,-0.502537,-0.502792,-0.531506,9.690035,9.767801,9.695569,9.700802,7.949555
117,2023-10-31,4,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,...,-1.036690,-1.007977,-1.047051,-1.047458,-1.094118,-9.168100,-9.072387,-9.146600,-9.147761,-9.205189
118,2023-11-01,4,0.269436,0.088505,16.192982,4133.333333,0.176253,2100.35,15383.333333,10788.208740,...,-0.457328,0.053240,-0.438325,-0.440578,-0.606281,9.638589,9.713963,9.640766,9.646963,7.473084

In [9]:
full_df.keys()
full_df = full_df.drop(columns=['value'])

In [10]:
full_df.isnull().sum()

datetime    0
user        0
HRV_CVNN    0
HRV_CVSD    0
HRV_HTI     0
           ..
z_last      0
z_max       0
z_mean      0
z_median    0
z_min       0
Length: 79, dtype: int64

In [11]:
list(full_df.dtypes)

[dtype('<M8[ns]'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64')]

In [12]:
final = pd.merge(full_df, val_label_copy, on=['user', 'datetime'], how='left')
final = final.dropna(subset=['Q1'])

final

,datetime,user,HRV_CVNN,HRV_CVSD,HRV_HTI,HRV_IQRNN,HRV_MCVNN,HRV_MadNN,HRV_MaxNN,HRV_MeanNN,...,z_median,z_min,date,Q1,Q2,Q3,S1,S2,S3,S4
0,2023-08-20,1,0.153625,0.109158,29.923077,3033.333333,0.176059,2347.45,21283.333333,13417.266495,...,9.157333,5.048856,2023-08-20,1.0,1.0,1.0,0.0,0.0,0.0,0.0
1,2023-08-21,1,0.144754,0.109095,24.848485,2233.333333,0.134971,1606.15,20833.333333,11963.211382,...,9.422935,5.424529,2023-08-21,1.0,1.0,1.0,0.0,0.0,1.0,0.0
2,2023-08-22,1,0.159191,0.125505,24.212121,2333.333333,0.140057,1729.70,27033.333333,12754.359616,...,8.160721,5.877969,2023-08-22,0.0,1.0,1.0,0.0,1.0,1.0,0.0
3,2023-08-23,1,0.202594,0.170459,34.590909,3033.333333,0.164074,2050.93,31250.000000,13062.658782,...,3.293720,-1.805385,2023-08-23,0.0,1.0,1.0,0.0,0.0,1.0,0.0
4,2023-08-24,1,0.141836,0.111380,30.038462,2783.333333,0.154237,1976.80,20000.000000,12995.646607,...,9.510274,6.374479,2023-08-24,1.0,1.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,2023-10-27,4,0.137746,0.100270,19.787879,2100.000000,0.118048,1457.89,16133.333333,12165.875447,...,8.684451,8.656933,2023-10-27,0.0,1.0,0.0,0.0,1.0,1.0,1.0
114,2023-10-28,4,0.130010,0.093182,19.028571,2354.166667,0.123229,1581.44,16666.666667,12598.848849,...,-4.264010,-4.357330,2023-10-28,1.0,1.0,0.0,1.0,1.0,1.0,1.0
115,2023-10-29,4,0.136587,0.096868,18.925000,2433.333333,0.127874,1704.99,17850.000000,13126.662263,...,0.579362,-4.528417,2023-10-29,1.0,1.0,0.0,0.0,1.0,1.0,1.0
116,2023-10-30,4,0.129085,0.098168,20.500000,2116.666667,0.123709,1606.15,16950.000000,12684.603659,...,9.700802,7.949555,2023-10-30,0.0,1.0,0.0,0.0,0.0,1.0,1.0
118,2023-11-01,4,0.269436,0.088505,16.192982,4133.333333,0.176253,2100.35,15383.333333,10788.208740,...,9.646963,7.473084,2023-11-01,1.0,1.0,0.0,0.0,1.0,1.0,1.0

In [13]:
# 결측치 비율 계산
missing_ratio = final.isnull().mean() * 100

# 결과 출력
# 결측치 비율을 데이터프레임으로 정리
missing_ratio_df = pd.DataFrame(missing_ratio, columns=['Missing Ratio (%)'])
missing_ratio_df

          Missing Ratio (%)
datetime                0.0
user                    0.0
HRV_CVNN                0.0
HRV_CVSD                0.0
HRV_HTI                 0.0
...                     ...
Q3                      0.0
S1                      0.0
S2                      0.0
S3                      0.0
S4                      0.0

[87 rows x 1 columns]

In [14]:
list(test)

['subject_id',
 'datetime',
 'x_last',
 'x_mean',
 'x_max',
 'x_min',
 'x_median',
 'y_last',
 'y_mean',
 'y_max',
 'y_min',
 'y_median',
 'z_last',
 'z_mean',
 'z_max',
 'z_min',
 'z_median',
 'speed_last',
 'speed_mean',
 'speed_max',
 'speed_min',
 'speed_median',
 'm_light',
 'heart_rate_last',
 'heart_rate_mean',
 'heart_rate_max',
 'heart_rate_min',
 'heart_rate_median',
 'w_light',
 'burned_calories',
 'distance',
 'running_steps',
 'speed',
 'steps',
 'step_frequency',
 'walking_steps',
 'm_activity',
 'altitude_last',
 'altitude_mean',
 'altitude_max',
 'altitude_min',
 'altitude_median',
 'latitude_last',
 'latitude_mean',
 'latitude_max',
 'latitude_min',
 'latitude_median',
 'longitude_last',
 'longitude_mean',
 'longitude_max',
 'longitude_min',
 'longitude_median',
 'day_location_entropy',
 'day_Movement_radius',
 'HRV_MeanNN',
 'HRV_SDNN',
 'HRV_SDANN1',
 'HRV_SDNNI1',
 'HRV_SDANN2',
 'HRV_SDNNI2',
 'HRV_SDANN5',
 'HRV_SDNNI5',
 'HRV_RMSSD',
 'HRV_SDSD',
 'HRV_CVNN',
 'HRV_CVSD',
 'HRV_MedianNN',
 'HRV_MadNN',
 'HRV_MCVNN',
 'HRV_IQRNN',
 'HRV_SDRMSSD',
 'HRV_Prc20NN',
 'HRV_Prc80NN',
 'HRV_pNN50',
 'HRV_pNN20',
 'HRV_MinNN',
 'HRV_MaxNN',
 'HRV_HTI',
 'HRV_TINN']

In [15]:
final.drop(columns=['date'],inplace=True)

In [16]:
import numpy as np

cols_to_replace = [
    'x_last', 'x_mean', 'x_max', 'x_min', 'x_median',
    'y_last', 'y_mean', 'y_max', 'y_min', 'y_median',
    'z_last', 'z_mean', 'z_max', 'z_min', 'z_median',
    'heart_rate_last', 'heart_rate_mean', 'heart_rate_max', 
    'heart_rate_min', 'heart_rate_median'
]

# Apply the replacement
final[cols_to_replace] = final[cols_to_replace].replace(0, np.nan)
test[cols_to_replace] = test[cols_to_replace].replace(0, np.nan)

In [17]:
%pip install fancyimpute

Requirement already satisfied: fancyimpute in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (0.7.0)
Requirement already satisfied: knnimpute>=0.1.0 in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from fancyimpute) (0.1.0)
Requirement already satisfied: scikit-learn>=0.24.2 in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from fancyimpute) (1.5.0)
Requirement already satisfied: cvxpy in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from fancyimpute) (1.5.1)
Requirement already satisfied: cvxopt in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from fancyimpute) (1.3.2)
Requirement already satisfied: pytest in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from fancyimpute) (8.2.2)
Requirement already satisfied: nose in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from fancyimpute) (1.3.7)
Requirement already satisfied: six in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from knnimpute>=0.1.0->fancyimpute) (1.16.0)
Requirement already satisfied: numpy>=1.10 in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from knnimpute>=0.1.0->fancyimpute) (1.24.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from scikit-learn>=0.24.2->fancyimpute) (1.9.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from scikit-learn>=0.24.2->fancyimpute) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from scikit-learn>=0.24.2->fancyimpute) (3.5.0)
Requirement already satisfied: osqp>=0.6.2 in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from cvxpy->fancyimpute) (0.6.7)
Requirement already satisfied: ecos>=2 in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from cvxpy->fancyimpute) (2.0.13)
Requirement already satisfied: clarabel>=0.5.0 in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from cvxpy->fancyimpute) (0.9.0)
Requirement already satisfied: scs>=3.2.4.post1 in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from cvxpy->fancyimpute) (3.2.4.post2)
Requirement already satisfied: iniconfig in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from pytest->fancyimpute) (2.0.0)
Requirement already satisfied: packaging in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from pytest->fancyimpute) (24.0)
Requirement already satisfied: pluggy<2.0,>=1.5 in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from pytest->fancyimpute) (1.5.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from pytest->fancyimpute) (1.2.1)
Requirement already satisfied: tomli>=1 in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from pytest->fancyimpute) (2.0.1)
Requirement already satisfied: colorama in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from pytest->fancyimpute) (0.4.6)
Requirement already satisfied: qdldl in c:\users\lty\appdata\local\anaconda3\envs\lee_ty\lib\site-packages (from osqp>=0.6.2->cvxpy->fancyimpute) (0.1.7.post2)
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
Note: you may need to restart the kernel to use updated packages.

WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.

In [18]:
final.reset_index(drop=True,inplace=True)
test.reset_index(drop=True, inplace=True)

In [19]:
from fancyimpute import IterativeImputer
from sklearn.tree import DecisionTreeRegressor
from sklearn.experimental import enable_iterative_imputer

# 사용자별 그룹화 후 트리 기반 MICE 보간 적용
def tree_based_mice_impute(group):
    # DecisionTreeRegressor를 사용하여 IterativeImputer 설정
    imputer = IterativeImputer(estimator=DecisionTreeRegressor(), random_state=0)
    imputed = imputer.fit_transform(group)
    return pd.DataFrame(imputed, index=group.index, columns=group.columns)

# 보간할 열 선택
columns_to_impute = final.columns.difference(['datetime'])

# 보간할 열만 선택하여 데이터프레임 생성
df_to_impute = final[columns_to_impute]

df_to_impute

(CVXPY) Jul 06 02:46:38 PM: Encountered unexpected exception importing solver CVXOPT:
ImportError('DLL load failed while importing base: 지정된 모듈을 찾을 수 없습니다.')
(CVXPY) Jul 06 02:46:38 PM: Encountered unexpected exception importing solver GLPK:
ImportError('DLL load failed while importing base: 지정된 모듈을 찾을 수 없습니다.')
(CVXPY) Jul 06 02:46:38 PM: Encountered unexpected exception importing solver GLPK_MI:
ImportError('DLL load failed while importing base: 지정된 모듈을 찾을 수 없습니다.')

,HRV_CVNN,HRV_CVSD,HRV_HTI,HRV_IQRNN,HRV_MCVNN,HRV_MadNN,HRV_MaxNN,HRV_MeanNN,HRV_MedianNN,HRV_MinNN,...,y_last,y_max,y_mean,y_median,y_min,z_last,z_max,z_mean,z_median,z_min
0,0.153625,0.109158,29.923077,3033.333333,0.176059,2347.45,21283.333333,13417.266495,13333.333333,7933.333333,...,0.413958,1.036092,0.428777,0.378066,-0.038285,9.165707,9.863214,8.861109,9.157333,5.048856
1,0.144754,0.109095,24.848485,2233.333333,0.134971,1606.15,20833.333333,11963.211382,11900.000000,6800.000000,...,-0.009571,0.181855,-0.013229,-0.014357,-0.339781,9.427721,9.872787,9.377162,9.422935,5.424529
2,0.159191,0.125505,24.212121,2333.333333,0.140057,1729.70,27033.333333,12754.359616,12350.000000,8333.333333,...,-1.746760,-0.062213,-1.750896,-1.751546,-2.050649,8.276774,9.643075,7.798959,8.160721,5.877969
3,0.202594,0.170459,34.590909,3033.333333,0.164074,2050.93,31250.000000,13062.658782,12500.000000,8850.000000,...,0.032901,0.537189,0.044782,0.043071,-1.094716,3.798606,9.402596,3.411778,3.293720,-1.805385
4,0.141836,0.111380,30.038462,2783.333333,0.154237,1976.80,20000.000000,12995.646607,12816.666667,9166.666667,...,-0.111266,0.105284,-0.112217,-0.110070,-0.356531,9.543774,9.872787,8.913097,9.510274,6.374479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,0.137746,0.100270,19.787879,2100.000000,0.118048,1457.89,16133.333333,12165.875447,12350.000000,7300.000000,...,0.035892,0.062213,0.038850,0.038285,-0.388535,8.689237,9.736694,8.683791,8.684451,8.656933
101,0.130010,0.093182,19.028571,2354.166667,0.123229,1581.44,16666.666667,12598.848849,12833.333333,7400.000000,...,0.153141,0.295813,0.147873,0.148355,-0.111864,-4.267001,-4.227519,-4.263600,-4.264010,-4.357330
102,0.136587,0.096868,18.925000,2433.333333,0.127874,1704.99,17850.000000,13126.662263,13333.333333,6900.000000,...,0.215952,0.338884,0.228002,0.197408,0.129212,0.581755,5.991777,0.579075,0.579362,-4.528417
103,0.129085,0.098168,20.500000,2116.666667,0.123709,1606.15,16950.000000,12684.603659,12983.333333,6750.000000,...,-0.499203,-0.364008,-0.502537,-0.502792,-0.531506,9.690035,9.767801,9.695569,9.700802,7.949555
104,0.269436,0.088505,16.192982,4133.333333,0.176253,2100.35,15383.333333,10788.208740,11916.666667,5350.000000,...,-0.457328,0.053240,-0.438325,-0.440578,-0.606281,9.638589,9.713963,9.640766,9.646963,7.473084

In [20]:
# 사용자별 그룹화하여 MICE 보간 적용
imputed_df = df_to_impute.groupby('user').apply(tree_based_mice_impute).reset_index(drop=True)

C:\Users\lty\AppData\Local\Temp\ipykernel_18356\719053338.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  imputed_df = df_to_impute.groupby('user').apply(tree_based_mice_impute).reset_index(drop=True)

In [21]:
# 원래 데이터프레임에 보간된 값 결합
final[columns_to_impute] = imputed_df

In [22]:
final

,datetime,user,HRV_CVNN,HRV_CVSD,HRV_HTI,HRV_IQRNN,HRV_MCVNN,HRV_MadNN,HRV_MaxNN,HRV_MeanNN,...,z_mean,z_median,z_min,Q1,Q2,Q3,S1,S2,S3,S4
0,2023-08-20,1.0,0.153625,0.109158,29.923077,3033.333333,0.176059,2347.45,21283.333333,13417.266495,...,8.861109,9.157333,5.048856,1.0,1.0,1.0,0.0,0.0,0.0,0.0
1,2023-08-21,1.0,0.144754,0.109095,24.848485,2233.333333,0.134971,1606.15,20833.333333,11963.211382,...,9.377162,9.422935,5.424529,1.0,1.0,1.0,0.0,0.0,1.0,0.0
2,2023-08-22,1.0,0.159191,0.125505,24.212121,2333.333333,0.140057,1729.70,27033.333333,12754.359616,...,7.798959,8.160721,5.877969,0.0,1.0,1.0,0.0,1.0,1.0,0.0
3,2023-08-23,1.0,0.202594,0.170459,34.590909,3033.333333,0.164074,2050.93,31250.000000,13062.658782,...,3.411778,3.293720,-1.805385,0.0,1.0,1.0,0.0,0.0,1.0,0.0
4,2023-08-24,1.0,0.141836,0.111380,30.038462,2783.333333,0.154237,1976.80,20000.000000,12995.646607,...,8.913097,9.510274,6.374479,1.0,1.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,2023-10-27,4.0,0.137746,0.100270,19.787879,2100.000000,0.118048,1457.89,16133.333333,12165.875447,...,8.683791,8.684451,8.656933,0.0,1.0,0.0,0.0,1.0,1.0,1.0
101,2023-10-28,4.0,0.130010,0.093182,19.028571,2354.166667,0.123229,1581.44,16666.666667,12598.848849,...,-4.263600,-4.264010,-4.357330,1.0,1.0,0.0,1.0,1.0,1.0,1.0
102,2023-10-29,4.0,0.136587,0.096868,18.925000,2433.333333,0.127874,1704.99,17850.000000,13126.662263,...,0.579075,0.579362,-4.528417,1.0,1.0,0.0,0.0,1.0,1.0,1.0
103,2023-10-30,4.0,0.129085,0.098168,20.500000,2116.666667,0.123709,1606.15,16950.000000,12684.603659,...,9.695569,9.700802,7.949555,0.0,1.0,0.0,0.0,0.0,1.0,1.0
104,2023-11-01,4.0,0.269436,0.088505,16.192982,4133.333333,0.176253,2100.35,15383.333333,10788.208740,...,9.640766,9.646963,7.473084,1.0,1.0,0.0,0.0,1.0,1.0,1.0

In [23]:
from fancyimpute import IterativeImputer
from sklearn.tree import DecisionTreeRegressor
from sklearn.experimental import enable_iterative_imputer

# 사용자별 그룹화 후 트리 기반 MICE 보간 적용
def tree_based_mice_impute(group):
    # DecisionTreeRegressor를 사용하여 IterativeImputer 설정
    imputer = IterativeImputer(estimator=DecisionTreeRegressor(), random_state=0)
    imputed = imputer.fit_transform(group)
    return pd.DataFrame(imputed, index=group.index, columns=group.columns)



# 보간할 열 선택
columns_to_impute2 = test.columns.difference(['datetime'])

# 보간할 열만 선택하여 데이터프레임 생성
df_to_impute2 = test[columns_to_impute2]

df_to_impute2

,HRV_CVNN,HRV_CVSD,HRV_HTI,HRV_IQRNN,HRV_MCVNN,HRV_MadNN,HRV_MaxNN,HRV_MeanNN,HRV_MedianNN,HRV_MinNN,...,y_last,y_max,y_mean,y_median,y_min,z_last,z_max,z_mean,z_median,z_min
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,...,0.175974,0.690727,0.184720,0.180762,-0.069432,1.954866,9.220370,2.085694,1.859098,-2.740164
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,...,0.414197,1.602918,0.440236,0.409408,0.016759,8.207623,9.700408,7.829025,8.241142,5.394436
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,...,0.156820,0.537498,0.168071,0.155623,-0.057461,9.694422,9.763854,9.687232,9.695619,8.503307
3,0.000000,0.000000,1.000000,0.000000,0.000000,0.000,10000.000000,10000.000000,10000.000000,10000.000000,...,0.210690,0.447716,0.217838,0.210690,-0.009577,9.617807,9.737517,9.567128,9.623793,8.413525
4,0.065087,0.006704,1.716329,16.666667,0.000000,0.000,12666.666667,12034.872685,12350.000000,10000.000000,...,0.294487,0.477643,0.300855,0.296881,0.117316,9.498097,9.663298,9.479809,9.498098,9.110237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,0.434131,0.138326,42.437500,13358.333333,0.167195,2050.930,31733.333333,16273.024055,12266.666667,8850.000000,...,0.186753,0.258582,0.185070,0.184359,-0.043097,9.840469,9.945818,9.821831,9.851244,7.398309
117,0.302278,0.344427,35.608696,1600.000000,0.105739,1161.370,28166.666667,12017.989418,10983.333333,8266.666667,...,4.680807,5.047131,4.672112,4.676019,0.408224,0.668003,7.500066,0.675419,0.670397,0.426181
118,0.368191,0.189787,39.083333,3241.666667,0.138156,1655.570,30316.666667,14361.265103,11983.333333,5516.666667,...,0.095771,0.155628,0.101851,0.100560,NaN,9.859624,9.938635,9.862771,9.862018,9.760261
119,0.422382,0.111454,45.181818,12400.000000,0.293555,3669.435,30316.666667,15269.517103,12500.000000,7066.666667,...,0.349564,0.859545,0.350324,0.348367,0.250202,1.367131,9.651321,1.092958,0.822433,-3.680000
120,0.384709,0.246143,27.500000,11116.666667,0.176211,2149.770,32250.000000,15774.449761,12200.000000,8066.666667,...,0.318439,0.362733,0.317787,0.316044,0.282524,9.550762,9.644139,9.543176,9.543579,9.437034

In [24]:
# 사용자별 그룹화하여 MICE 보간 적용
imputed_df2 = df_to_impute2.groupby('subject_id').apply(tree_based_mice_impute).reset_index(drop=True)

# 원래 데이터프레임에 보간된 값 결합
test[columns_to_impute2] = imputed_df2

C:\Users\lty\AppData\Local\anaconda3\envs\lee_ty\lib\site-packages\sklearn\impute\_iterative.py:825: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(
C:\Users\lty\AppData\Local\Temp\ipykernel_18356\1939101512.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  imputed_df2 = df_to_impute2.groupby('subject_id').apply(tree_based_mice_impute).reset_index(drop=True)

In [25]:
test

,subject_id,datetime,x_last,x_mean,x_max,x_min,x_median,y_last,y_mean,y_max,...,HRV_IQRNN,HRV_SDRMSSD,HRV_Prc20NN,HRV_Prc80NN,HRV_pNN50,HRV_pNN20,HRV_MinNN,HRV_MaxNN,HRV_HTI,HRV_TINN
0,5.0,2023-11-05,-0.040701,-0.065710,1.574188,-1.702277,-0.064643,0.175974,0.184720,0.690727,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1,5.0,2023-11-06,0.028730,0.003530,1.690306,-0.938527,0.019752,0.414197,0.440236,1.602918,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
2,5.0,2023-11-07,0.052672,0.038821,0.417788,-0.201113,0.041899,0.156820,0.168071,0.537498,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
3,5.0,2023-11-08,-0.059855,-0.066900,0.238223,-0.715866,-0.069432,0.210690,0.217838,0.447716,...,0.000000,0.000000,10000.000000,10000.000000,0.000000,0.000000,10000.000000,10000.000000,1.000000,0.0
4,5.0,2023-11-09,-0.390255,-0.376375,0.055067,-1.380257,-0.375890,0.294487,0.300855,0.477643,...,16.666667,9.708690,12333.333333,12350.000000,0.208333,0.208333,10000.000000,12666.666667,1.716329,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,8.0,2023-11-05,0.126897,0.118722,0.265765,0.011971,0.119714,0.186753,0.185070,0.258582,...,13358.333333,3.138471,11100.000000,25966.666667,93.667158,94.256259,8850.000000,31733.333333,42.437500,0.0
117,8.0,2023-11-06,-1.893871,-1.592407,0.011971,-8.382356,-1.468888,4.680807,4.672112,5.047131,...,1600.000000,0.877626,10150.000000,12200.000000,91.330891,93.162393,8266.666667,28166.666667,35.608696,0.0
118,8.0,2023-11-07,0.189148,0.188317,0.284919,0.099362,0.189148,0.095771,0.101851,0.155628,...,3241.666667,1.940019,10983.333333,19526.666667,82.622601,83.475480,5516.666667,30316.666667,39.083333,0.0
119,8.0,2023-11-08,0.385478,0.383590,0.823631,0.325621,0.385478,0.349564,0.350324,0.859545,...,12400.000000,3.789745,10050.000000,24100.000000,83.501006,84.708249,7066.666667,30316.666667,45.181818,0.0
120,8.0,2023-11-09,0.395055,0.397442,0.438152,0.361536,0.397450,0.318439,0.317787,0.362733,...,11116.666667,1.562951,11100.000000,23000.000000,94.928230,95.023923,8066.666667,32250.000000,27.500000,0.0

In [26]:
val_stats_path = 'val_24hr_median_df_0628.csv'

final.to_csv(val_stats_path, index=False)

In [27]:
test_stats_path = 'test_24hr_median_df_0628.csv'
test.to_csv(test_stats_path, index=False)